<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18831" started-at="2022-02-26T23:17:35 IST" finished-at="2022-02-26T23:17:54 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18831" started-at="2022-02-26T23:17:35 IST" finished-at="2022-02-26T23:17:54 IST">
      <class name="testCases.AddToCartTC01">
        <test-method status="PASS" signature="openBrowser2()[pri:0, instance:testCases.AddToCartTC01@18bf3d14]" name="openBrowser2" is-config="true" duration-ms="15392" started-at="2022-02-26T23:17:35 IST" finished-at="2022-02-26T23:17:51 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser2 -->
        <test-method status="FAIL" signature="loginmethod()[pri:1, instance:testCases.AddToCartTC01@18bf3d14]" name="loginmethod" duration-ms="2939" started-at="2022-02-26T23:17:51 IST" finished-at="2022-02-26T23:17:54 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test case failed, user not logged in expected [https://www.flipkart.com/] but found [https://www.flipkart.com/account/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test case failed, user not logged in expected [https://www.flipkart.com/] but found [https://www.flipkart.com/account/login]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testCases.AddToCartTC01.loginmethod(AddToCartTC01.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginmethod -->
        <test-method status="SKIP" signature="SearchAndAddToCart()[pri:0, instance:testCases.AddToCartTC01@18bf3d14]" name="SearchAndAddToCart" duration-ms="0" started-at="2022-02-26T23:17:54 IST" depends-on-methods="testCases.AddToCartTC01.loginmethod" finished-at="2022-02-26T23:17:54 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AddToCartTC01.SearchAndAddToCart()[pri:0, instance:testCases.AddToCartTC01@18bf3d14] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AddToCartTC01.SearchAndAddToCart()[pri:0, instance:testCases.AddToCartTC01@18bf3d14] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchAndAddToCart -->
      </class> <!-- testCases.AddToCartTC01 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
